import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import tenantsRouter from "./tenants";
import departmentsRouter from "./departments";
import usersRouter from "./users";
import rolesRouter from "./roles";
import permissionsRouter from "./permissions";
import auditLogsRouter from "./auditLogs";
import identityStatsRouter from "./identityStats";
import workflowDefinitionsRouter from "./workflowDefinitions";
import workflowVersionsRouter from "./workflowVersions";
import workflowInstancesRouter from "./workflowInstances";
import workflowTasksRouter from "./workflowTasks";
import workflowHistoryRouter from "./workflowHistory";
import rulesRouter from "./rules";
import ruleVersionsRouter from "./ruleVersions";
import ruleHistoryRouter from "./ruleHistory";
import formsRouter from "./forms";
import formVersionsRouter from "./formVersions";
import formSubmissionsRouter from "./formSubmissions";
import notificationTemplatesRouter from "./notificationTemplates";
import notificationsRouter from "./notifications";
import notificationPreferencesRouter from "./notificationPreferences";
import documentTemplatesRouter from "./documentTemplates";
import documentsRouter from "./documents";
import attachmentsRouter from "./attachments";
import searchRouter from "./search";
import integrationsRouter from "./integrations";
import reportsRouter from "./reports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(tenantsRouter);
router.use(departmentsRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(permissionsRouter);
router.use(auditLogsRouter);
router.use(identityStatsRouter);
router.use(workflowDefinitionsRouter);
router.use(workflowVersionsRouter);
router.use(workflowInstancesRouter);
router.use(workflowTasksRouter);
router.use(workflowHistoryRouter);
router.use(rulesRouter);
router.use(ruleVersionsRouter);
router.use(ruleHistoryRouter);
router.use(formsRouter);
router.use(formVersionsRouter);
router.use(formSubmissionsRouter);
router.use(notificationTemplatesRouter);
router.use(notificationsRouter);
router.use(notificationPreferencesRouter);
router.use(documentTemplatesRouter);
router.use(documentsRouter);
router.use(attachmentsRouter);
router.use(searchRouter);
router.use(integrationsRouter);
router.use(reportsRouter);

export default router;
